richpolis_backend:
    resource: "@RichpolisBackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

richpolis_gal_mon:
    resource: "@RichpolisGalMonBundle/Controller/"
    type:     annotation
    prefix:   /

genemu_upload:
    resource: "@GenemuFormBundle/Resources/config/routing/upload.xml"

genemu_image:
    resource: "@GenemuFormBundle/Resources/config/routing/image.xml"

login:
    pattern:   /login
    defaults:  { _controller: RichpolisBackendBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
    
_imagine:
    resource: .
    type:     imagine


# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
