jms_security_extra:
    secure_all_services: false
    expressions: true

security:
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

#    providers:
#        in_memory:
#            users:
#                jerryml:  { password: jerryml01, roles: [ 'ROLE_USER' ] }
#                richpolis: { password: D3m3s1s1, roles: [ 'ROLE_ADMIN' ] }
                
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false

#        login:
#            pattern:  ^/demo/secured/login$
#            security: false

#        secured_area:
#            pattern:    ^/demo/secured/
#            form_login:
#                check_path: /demo/secured/login_check
#                login_path: /demo/secured/login
#            logout:
#                path:   /demo/secured/logout
#                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

 #   access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /backend
 
    access_control:
        - { path: ^/backend, roles: ROLE_ADMIN }
 
    providers:
        main:
            entity: { class: Richpolis\GalMonBundle\Entity\Usuarios, property: username }
 
    encoders:
        Richpolis\GalMonBundle\Entity\Usuarios: sha512