<?php

namespace Richpolis\GalMonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClubsFansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubsFansRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT COUNT(cf.posicion) as value 
            FROM RichpolisGalMonBundle:ClubsFans cf 
            ORDER BY cf.posicion ASC
            ');
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
      
    public function getQueryClubsFansActivas($todas=false){
        $em=$this->getEntityManager();
        if(!$todas){
            $query=$em->createQuery('
                SELECT f 
                FROM RichpolisGalMonBundle:ClubsFans f 
                WHERE f.isActive=:active 
                ORDER BY f.club, f.presidente,f.createdAt ASC
           ')->setParameter('active', true);
        }else{
            $query=$em->createQuery('
                SELECT f 
                FROM RichpolisGalMonBundle:ClubsFans f 
                ORDER BY f.club, f.presidente,f.createdAt ASC
           ');
        }
        return $query;
    }
    
    public function getClubsFansActivas($todas=false){
        $query=$this->getQueryClubsFansActivas($todas);
        return $query->getResult();
    }
}