<?php

namespace Richpolis\GalMonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClubsFansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubsFansRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT COUNT(cf.posicion) as value 
            FROM RichpolisGalMonBundle:ClubsFans cf 
            ORDER BY cf.posicion ASC
            ');
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
      
    public function getQueryClubsFansActivas($todas=false){
        $query=$this->createQueryBuilder('c')
                    ->orderBy('c.posicion', 'DESC');
        if(!$todas){
            $query->where('c.isActive=:active')
                  ->setParameter('active', true);
        }
        return $query->getQuery();
    }
    
    public function getClubsFansActivas($todas=false){
        $query=$this->getQueryClubsFansActivas($todas);
        return $query->getResult();
    }
}