<?php

namespace Richpolis\GalMonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FansRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FansRepository extends EntityRepository
{
    public function getMaxPosicion(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT COUNT(f.posicion) as value 
            FROM RichpolisGalMonBundle:Fans f 
            ORDER BY f.posicion ASC
            ');
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
       
    public function getQueryFansActivas($todas=false){
        $query=$this->createQueryBuilder('f')
                    ->orderBy('f.posicion', 'DESC');
        if(!$todas){
            $query->where('f.isActive=:active')
                  ->setParameter('active', true);
        }
        return $query->getQuery();
    }
    
    public function getFansActivas($todas=false){
        $query=$this->getQueryFansActivas($todas);
        return $query->getResult();
    }
}