<?php

namespace Richpolis\GalMonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PublicacionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionesRepository extends EntityRepository
{
    public function getMaxPosicion($tipo){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT COUNT(p.posicion) as value 
            FROM RichpolisGalMonBundle:Publicaciones p 
            WHERE p.tipoPublicacion=:tipo 
            ORDER BY p.posicion ASC
            ')->setParameter('tipo', $tipo);
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    public function getQueryPublicacionesPorTipoYActivas($tipo,$todas=false){
        $query=$this->createQueryBuilder('p')
                    ->where('p.tipoPublicacion=:tipo')
                    ->setParameter('tipo', $tipo)
                    ->orderBy('p.posicion', 'DESC');
        if(!$todas){
            $query->andWhere('p.isActive=:active')
                  ->setParameter('active', true);
        }
        return $query->getQuery();
    }
    
    public function getPublicacionesPorTipoYActivas($tipo,$todas=false){
        $query=$this->getQueryPublicacionesPorTipoYActivas($tipo,$todas);
        return $query->getResult();
    }
}