<?php

namespace Richpolis\GalMonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PublicidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicidadRepository extends EntityRepository
{
    public function getMaxPosicion($tipo){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
            SELECT MAX(p.posicion) as value 
            FROM RichpolisGalMonBundle:Publicidad p 
            WHERE p.tipoPublicidad=:tipo 
            ORDER BY p.posicion ASC
            ')->setParameter('tipo', $tipo);
        $max=$query->getResult();
        return $max[0]['value'];
    }
    
    public function getQueryPublicidadPorTipoYActivas($tipo,$todas=false){
        $query=$this->createQueryBuilder('p')
                    ->where('p.tipoPublicidad=:tipo')
                    ->setParameter('tipo', $tipo)
                    ->orderBy('p.activedAt', 'DESC');
        if(!$todas){
            $query->andWhere('p.isActive=:active')
                  ->setParameter('active', true);
        }
        return $query->getQuery();
    }
    
    public function getPublicidadPorTipoYActivas($tipo,$todas=false){
        $query=$this->getQueryPublicidadPorTipoYActivas($tipo,$todas);
        return $query->getResult();
    }

    
    public function getFechaInactivedAtMax(){
        $query=$this->getEntityManager()->createQueryBuilder();
        $query->select($query->expr()->Max('p.inativedAt'))
              ->from('RichpolisGalMonBundle:Publicidad', 'p');
        return $query->getQuery()->getSingleResult();
    }
    
    
    public function getPublicidadActuales(){
        $em=$this->getEntityManager();
        $query=$em->createQuery('
                    SELECT p 
                    FROM RichpolisGalMonBundle:Publicidad p 
                    GROUP BY p.tipoPublicidad 
                    ORDER BY p.tipoPublicidad,p.posicion DESC 
                ');
        return $query->getResult();
    }
}