<?php

namespace Richpolis\GalMonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VideosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideosRepository extends EntityRepository
{
    public function getMaxPosicion() {
        $em = $this->getEntityManager();
        $query = $em->createQuery('
            SELECT COUNT(v.posicion) as value 
            FROM RichpolisGalMonBundle:Videos v 
            ORDER BY v.posicion ASC
            ');
        $max = $query->getResult();
        return $max[0]['value'];
    }
    
    public function getQueryVideosActivas($todas=false){
        $query=$this->createQueryBuilder('v')
                    ->orderBy('v.posicion', 'ASC');
        if(!$todas){
            $query->andwhere('v.isActive=:active')
                  ->setParameter('active', true);
        }
        return $query->getQuery();
    }
    
    public function getVideosActivas($todas=false){
        $query=$this->getQueryVideosActivas($todas);
        return $query->getResult();
    }
}